# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessMaster',
            fields=[
                ('access_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('access_name', models.CharField(max_length=30)),
                ('access_email', models.CharField(max_length=100)),
            ],
        ),
    ]
